// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using database1.Models;

#nullable disable

namespace database1.Migrations
{
    [DbContext(typeof(EmpContext))]
    [Migration("20260430094911_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("database1.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("password");

                    b.Property<int?>("Roleid")
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    b.Property<string>("Username")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK__login__3214EC07CE89C6DF");

                    b.HasIndex("Roleid");

                    b.ToTable("login", (string)null);
                });

            modelBuilder.Entity("database1.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Rname")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("rname");

                    b.HasKey("Id")
                        .HasName("PK__Role__3214EC07AF0DBE76");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("database1.Models.Login", b =>
                {
                    b.HasOne("database1.Models.Role", "Role")
                        .WithMany("Logins")
                        .HasForeignKey("Roleid")
                        .HasConstraintName("FK_login_ToTable");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("database1.Models.Role", b =>
                {
                    b.Navigation("Logins");
                });
#pragma warning restore 612, 618
        }
    }
}
